name: Teste VR

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows 11]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [3.2.2-1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install operating system dependencies
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@ale
        # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
             gem install cucumber
             gem install httparty
             bundler install
             bundle exec cucumber
